### ISSUE TITLE
Lots of Jitter when using over 64 WS2812B LEDs with ESP8266

### ISSUE THREAD

**Issue by dudesky71** [jasoncoon/esp8266-fastled-webserver#85] opened 2018-08-09 15:49 UTC
Jason, I have a 128 WS2812B 16x8 matrix connected in a non-serpentine format. When I run your webserver code I get jitter. Im using a level shifter. I noticed that when I set "NUM_LEDS" to anything over 69 when the ESP starts up, it fills everything with a solid color and i get jitter when the twinkle animations run. If i set "NUM_LEDS" to 64 for example, only 64 initialize at startup as it should and its perfectly smooth on twinkle animations. I've played with frame rate and everything I can think of including shutting off wifi and disabling interupts but nothing fixes this. Its running on a battery. There is no DC noise or current issues. If I run "NoisePalette" sketch from the fastled.io website, I can run all 128 LEDs super fast with no jitter on any animation. This proves the hardware works fine. Can you take a look and see if this is a memory allocation bug or something? I really love your implementation but I'm not sure how to fix it myself :)

Thanks!
-K

**Comment by jasoncoon** [comment] 2018-08-09 16:22
Tried different values for these, before the FastLED include?

#define FASTLED_INTERRUPT_RETRY_COUNT 0
#define FASTLED_ALLOW_INTERRUPTS 0

https://github.com/FastLED/FastLED/issues/367#issuecomment-259504657

**Comment by dudesky71** [comment] 2018-08-09 16:32
Jason,
Thank you for the fast reply. I've tried the above definitions with different values. In fact, without them I get jitter no matter how many LEDs are defined (even with 64). I have the latest source and libraries. I've also tried compiling on two seperate machines running Arduino 1.6.10 and 1.8.5. Windows and MAC versions as well. There is something else going on.
-K

**Comment by tobi01001** [comment] 2018-08-09 16:43
You may have a look at this fork enabling DMA for esp8266 within fastled.

You will be limited to just the one I/O with DMA but it is working great
without any jitter...


https://github.com/coryking/FastLED.git

Without DMA I had jitter all over the strips as well.


dudesky71 <notifications@github.com> schrieb am Do., 9. Aug. 2018, 18:32:

**Comment by dudesky71** [comment] 2018-08-09 17:09
Hey thanks tobi! If i use this will the frame rate be limited at all? un fortunately my hardware doesn't use this pin for the LED date. It will require a board spin :(

**Comment by tobi01001** [comment] 2018-08-09 17:44
There is no always a limit defined by the led strip type and the number of
leds (writing out the data). But with DMA no one has to wait for that....

The problem is more with the interrupts required for e.g. Wifi but with DMA
I had the webserver running with 250 leds and. framerate of 100 without any
issue.

dudesky71 <notifications@github.com> schrieb am Do., 9. Aug. 2018, 19:09:

**Comment by dudesky71** [comment] 2018-08-09 18:05
Tobi, I totally agree with you but that doesn't explain why the unmodified examples from the fastled.io website just work on my same hardware out of the gate on the same GPIO that has no DMA.

**Comment by tobi01001** [comment] 2018-08-09 20:11
If the examples go without WiFi / additional tasks driven by interrupts it
may still be an explanation for the behavior seen.

Once (rather intensive) interrupt tasks kick in, the writing of the Leds
will be interrupted fir the time the task runs. For short ISRs this may be
no problem but as soon as they affect the timing, you may habe jitter.

If it works without interrupts (interrupts disabled), then DMA may do the
trick (as it did for me).

Regards, Toby

dudesky71 <notifications@github.com> schrieb am Do., 9. Aug. 2018, 20:05:

**Comment by dudesky71** [comment] 2018-08-10 12:27
By chance is there a branch of this code that doesn't use wifi at all and just cycles through the animations manually? That would be a good test as well since the other FastLED animations work fine.

**Comment by jasoncoon** [comment] 2018-08-10 12:51
That's pretty much DemoReel100: https://github.com/FastLED/FastLED/blob/master/examples/DemoReel100/DemoReel100.ino

If that doesn't exhibit the same issue, you could copy over and add any patterns to it.

I'll try to perform some tests today.  It's been a while since I went through setting up a new esp8266-fastled-webserver project from scratch.

**Comment by jasoncoon** [comment] 2018-08-11 14:04
Sorry, just to confirm, have you tried:

```
#define FASTLED_INTERRUPT_RETRY_COUNT 1
#define FASTLED_ALLOW_INTERRUPTS 1

#include <FastLED.h>
```

at the very top of your sketch?

**Comment by jasoncoon** [comment] 2018-08-11 16:04
Mind trying this simplified branch?  https://github.com/jasoncoon/esp8266-fastled-webserver/tree/v1.0-no-ir

**Comment by dudesky71** [comment] 2018-08-11 18:01
Jason,

Also, it seems to do it only on the twinkle animations and this branch doesn't really have any. However, It does have alot of jitter on the confetti animation.

-K

**Comment by jasoncoon** [comment] 2018-10-06 18:12
Try again with the latest from master?

I just ran through a test setup and was seeing jitter on anything over 50 LEDs.  I nearly eliminated it by doing the following:
* adjusted the FastLED interrupt options to what's currently in master
* switched from powering over USB
* updated to the latest:
  * arduino
  * fastled library
  * esp8266 board and libraries

**Comment by jasoncoon** [comment] 2018-10-07 16:32
Also, in loop(), try replacing

`FastLED.delay(1000 / FRAMES_PER_SECOND)`

with 

`delay(1000 / FRAMES_PER_SECOND)`

If that doesn't work, also try reducing FRAMES_PER_SECOND from 120 to 60.

**Comment by tstill88** [comment] 2018-11-08 01:43
https://youtu.be/AxHRdYMEOiQ

I'm getting this issue with 2812B. I've tried all of the above but regardless on LED length I'm getting that flashing/ jitter

Just updated to latest IDE and now using 5v USB plug rather than from laptop.

**Comment by jasoncoon** [comment] 2018-11-08 01:45
@tstill88 are you using a level shifter?

**Comment by tstill88** [comment] 2018-11-08 02:15
No not using a low level shifter and power is justvia Usb

**Comment by tstill88** [comment] 2018-11-08 12:17
I ordered a new strip that arrived today which was just 1m 60 LEDS and im getting no jitter on that, so maybe its the strip length thats the issue. I thought defining the amount of LED's in the sketch would limit the amount of power required when i had my 3m strip of 200+ LEDs connected. Should i maybe connected another USB power at the other end of my long strip?

**Comment by dudesky71** [comment] 2018-11-08 13:23
tstill88... It's been my experience that you just can't run more than 64 LEDs with this sketch. Jason has been very helpful and has released some forks for me to try but none of them work. My diligent research has uncovered the issue. The WiFi stack uses significant resources and needs some interrupt time on the MCU. When the LEDs exceed 64, the MCU has too much to process along with WiFi. Yield statements do not help this situation. If you look around on GitHub you will find some code that utilizes the DMA memory that is used for the UART pin. This is the ONLY pin that can output "SMOOTH" data to the LEDs. It acts like a "Cache Buffer" if you will that allows the WiFi to "Hog" the resources when needed but not enough to empty the buffer which outputs a constant stream to the LEDs regardless of what background processes are running :)

**Comment by jasoncoon** [comment] 2018-11-08 15:08
@tstill88 a level shifter may help.  ESP8266 output 3.3v logic levels, but the LEDs require 5v logic.  You might also try measuring the voltage (between 5V and GND) at the far end of your strip.  If it's below 5v, it'd help to connect 5V and GND at that end as well.

@dudesky71 sorry you're still having issues.  I have built a lot of pieces using much more than 64 LEDs, all with ESP8266 and variants of this sketch.  I've built 2D and 3D fibonacci pieces with 100 and 200 LEDs.  I've tested parallel output with 1,200 LEDs split between 4 and 6 outputs, for a total of 300 and 200 LEDs per pin.  I've always been able to eliminate the flicker.

I wonder if something in the ESP8266 libraries has changed lately?  Have you reduced the framerate, tried using delay instead of FastLED.delay, etc, to try to reduce the amount of time spent in interrupt?  Are you using long data wires to cover long distances between the ESP8266 and LEDs?  Have you tried using CAT5 or CAT6 cable to reduce noise and ringing?

**Comment by dudesky71** [comment] 2018-11-08 15:36
@jasoncoon I have also successfully ran more than 64 LEDs on ESP8266. On the particular project I keep having issues is a custom PCB with 128 LEDs on it. Other sketches run completely fine with no jitter. I'm using a level shifter from TI that works great. The connection from the ESP to the first LED is only 3 inches using a 10 mil trace. Each LED has a .1uF decoupling capacitor right at the LED. It also runs on a battery power source so there is absolutely no power supply noise. There is no wiring involved. This is all on a PCB. I have not tried using delay instead of FastLED.delay. Expressif recommends to not use ANY "Blocking" delays at all as this will crash the WiFi stack. Non-Blocking delays are the only way to go... I haven't fully looked at your code. Does it include "Blocking" delays?

**Comment by jasoncoon** [comment] 2018-11-08 15:42
@dudesky71 delay on ESP8266 internally calls esp_yield: https://github.com/esp8266/Arduino/issues/1410#issuecomment-170777719

So on ESP8266, in long running functions, loops, etc, it's actually better to use short calls to delay than to use FastLED.delay which will use up the time to refresh the LEDs.

**Comment by tstill88** [comment] 2018-11-08 22:43
Thanks Jason. Is there any guide I could check for using the level shifter with the nodemcu? Quite new to this!

**Comment by jasoncoon** [comment] 2018-11-09 02:30
No problem, hope you get it working!  Here's how you wire up a level shifter:

https://community.openhab.org/t/nodemcu-mqtt-led-strip-controller-build-config-how-to-videos/39902/23

I wouldn't bother trying to use anything except 74HCT125 or 74HCT245.  Most level shifters are not fast enough to handle WS2812 or APA102 data rates.

I don't have anything for NodeMCU ESP8266, but I do have a variety of level shifter shields for other ESP8266 and ESP32 boards: https://www.tindie.com/stores/jasoncoon/

**Comment by jasoncoon** [comment] 2018-11-09 15:10
1. Level shifter should be connected to 5v, ideally with a 0.1uF decoupling capacitor connected directly to the 5V and GND on the level shifter.  The level shifter is going to convert the 3.3v logic on the data pins to 5v.
2. Each LED can theoretically draw a max of 60mA each, at full brightness, solid white.  So 300 LEDs  could draw 18A.  Of course, you likely won't be driving them at max, and you can always limit the max power with FastLED.  These 5V 10A power supplies are known good: https://www.adafruit.com/product/658 . I've also used these before: https://amzn.to/2RO0713

**Comment by tstill88** [comment] 2018-11-09 19:31
Thanks again mate, i got it now :)

That second link is ideal actually as it comes with the female connector, just what I was looking for :) Once I have those bits hooked up I will let you know if the issue is sorted, sure it will be!

**Comment by maik-dmxc** [comment] 2019-02-02 17:50
Workaround

switching from
`FastLED.delay(1000 / FRAMES_PER_SECOND);`
to
`delay(1000 / FRAMES_PER_SECOND);`

stop the jitter on all patterns, but reduce the framerate as seen in the picture

![ds1z_quickprint19](https://user-images.githubusercontent.com/8010861/52167447-5e3a7380-271b-11e9-9513-d7120dd6d250.png)


regards maik

**Comment by maik-dmxc** [comment] 2019-02-02 18:16
could this the problem? found on [](https://plus.google.com/+AndrewTuline/posts/4BUgrkWgmdj)
`FastLED.delay() basically always does { delay(1); FastLED.show() }.  There are two cases where it doesn't:
(1) if the delay value == 0, then FastLED.show() is NOT called by FastLED.delay()
(2) if the delay value == 1 AND the millis() timer ticks between the first read and the second read inside delay(), then show() will NOT be called.

But if the delay value is 2 or more, FastLED.delay() calls FastLED.show().
`

regards

**Comment by dudesky71** [comment] 2019-02-02 18:20
Hello,

I like where you are going with this! I’ve had issues with all versions of code. This could be the fix. Jason, can you confirm?

Thanks
Kyle!

On Feb 2, 2019, at 1:16 PM, maik-dmxc <notifications@github.com<mailto:notifications@github.com>> wrote:


could this the problem? found on <https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplus.google.com%2F%2BAndrewTuline%2Fposts%2F4BUgrkWgmdj&data=02%7C01%7C%7C42cf1c972b9844d60ac908d6893a8b6a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636847281864693934&sdata=%2BMnuEWrZTF2thIrcHenSm0z4DtJEsjB7tmRdxcP1CJI%3D&reserved=0>
`FastLED.delay() basically always does { delay(1); FastLED.show() }. There are two cases where it doesn't:
(1) if the delay value == 0, then FastLED.show() is NOT called by FastLED.delay()
(2) if the delay value == 1 AND the millis() timer ticks between the first read and the second read inside delay(), then show() will NOT be called.

But if the delay value is 2 or more, FastLED.delay() calls FastLED.show().
`

regards

**Comment by AlirezaAbdiyan** [comment] 2019-04-11 07:05
I add `#define FASTLED_INTERRUPT_RETRY_COUNT 0` before `#include<FastLED.h>` and change line 19
[https://github.com/FastLED/FastLED/blob/master/platforms/esp/8266/clockless_esp8266.h](https://github.com/FastLED/FastLED/blob/master/platforms/esp/8266/clockless_esp8266.h)
from:
`template <int DATA_PIN, int T1, int T2, int T3, EOrder RGB_ORDER = RGB, int XTRA0 = 0, bool FLIP = false, int WAIT_TIME = 50>`
to:
`template <int DATA_PIN, int T1, int T2, int T3, EOrder RGB_ORDER = RGB, int XTRA0 = 0, bool FLIP = false, int WAIT_TIME = 5>`
Then the problem solved...

**Comment by tripdragon** [comment] 2019-04-17 04:46
Can atest for AlirezaAbdiyan. This Seems to have worked for our setup.
Specs 720 lights (3 per one ws2811b chip)
esp8266 controller
custom sin maths and cylon code demos
LOTS of power in links, NO ethernet < that one seems to cause issues with and SUPEr without a 100 ohm thingy
Still digging for performance tweaks

**Comment by jordanadania** [comment] 2020-04-23 20:40
So far, the best combination of changes for me has been:

- `#define FASTLED_ALLOW_INTERRUPTS 0` before `#include <FastLED.h>`
-  Disabling `Serial.begin(115200)`
- `yield()` after `FastLED.show()`
- CPU Frequency from 80 Mhz to 160 Mhz

I plan on testing Alireza Abdiyan's solution if I see anymore jitters.

**Comment by henrygab** [comment] 2021-11-27 00:39
Closing due to >1 year inactivity.

**Closed by henrygab** 2021-11-27 00:39 UTC
