### ISSUE TITLE
Verify and compile error 

### ISSUE THREAD

**Issue by DRussell1982** [jasoncoon/esp8266-fastled-webserver#205] opened 2021-06-20 09:55 UTC
hi i have been using the fast led for a while last time i used it at Christmas was working fine  now i want to extend the number of leds but it wont verify and come up with the errors below 

the spiffs download fine and i have com's with the board 

any help apprecated

In file included from C:\led\esp8266-nanoleaf-webserver-1.0\esp8266-fastled-webserver\libraries\FastLED/FastLED.h:42:0,

                 from C:\led\esp8266-nanoleaf-webserver-1.0\esp8266-fastled-webserver\esp8266-fastled-webserver.ino:63:

C:\led\esp8266-nanoleaf-webserver-1.0\esp8266-fastled-webserver\libraries\FastLED/platforms.h:22:2: error: #error "XTENSA-architecture microcontrollers are not supported"

 #error "XTENSA-architecture microcontrollers are not supported"

  ^

exit status 1
Error compiling for board WeMos D1 R2 & mini.

**Comment by henrygab** [comment] 2021-11-26 06:47
Hi @DRussell1982 ... 

Your error message above suggests that you are using FastLED, and that the above error message is coming from FastLED.  I'd normally suggest asking in their repository, but I first note that the above error message isn't in any recent versions of FastLED that I could find.  Therefore, I would first suggest you verify the version of FastLED you are using ... and where that header file is coming from.  Maybe something installed a (really) old version of the FastLED library?

Without more, I think this issue should be closed as it does not appear caused by anything in this library.

**Comment by jasoncoon** [comment] 2021-11-26 15:29
Agreed, looks like an old version of FastLED: https://github.com/FastLED/FastLED/issues/264

There should be a pragma warning above this error with the version of FastLED.

**Closed** 2021-11-26 19:21 UTC
Labels: wontfix, external
