### ISSUE TITLE
MSGEQ7

### ISSUE THREAD

**Issue by zombodotcom** [jasoncoon/esp8266-fastled-webserver#14] opened 2017-01-18 19:04 UTC
Hey, I saw in one of the other issues you were talking about the MSGeq7, I am trying to get this to work. I know there is only one analog pin on the esp8266, but would you be willing to post some of your patterns or drafts you were doing for msgeq7 support? id be very interested to look at them. I know you have torch, But I am trying to run a long ws2812b Around a room and i have been looking for some way to change them from matrix to just a single strand.

Thanks again for all your awesome work, I really appreciate what you do

**Comment by terrag42** [comment] 2017-02-27 17:29
I'd also like to be able to integrate LED patterns that use the analog input.

**Comment by jasoncoon** [comment] 2017-03-07 15:24
Closing, duplicate of https://github.com/jasoncoon/esp8266-fastled-webserver/issues/5

**Closed by jasoncoon** 2017-03-07 15:24 UTC
